### ISSUE TITLE
Luban 4.4.0 and 4.3.2 freezes on "Generate G-code and Preview"

### ISSUE THREAD

**Issue by jaydeedub** [Snapmaker/Luban#1746]
To make it simple and to eliminate user error, I chose the Sign CNC project from the Case Library.  and chose Vector processing mode.  I then select the single Vector Toolpath-1, and leave all the tool Parameters at default.  
Next, I select Generate G-code and preview, and a pop-up appears with two checkboxes, Toolpath and Simulation.  Toolpath is shown checked and Simulation is not.  It does nothing else.   The menus still seem functional, and I am able to close preview.
Meanwhile the console says:
`slice ()
cmd: /home/joe/bin/snapmaker-luban-4.4.0-linux-x64/resources/app/node_modules/snapmaker-lunar/engine/Linux/LunarTPP slicecnc -v -p -j /home/joe/.config/snapmaker-luban/Tmp/settings_12328014.json -l /home/joe/.config/snapmaker-luban/Tmp -o /home/joe/.config/snapmaker-luban/Tmp
2022-10-13T23:12:19.363Z - error laser-cnc-slice LunarTPP slice error, Code: 0 | Msg: Failed to load model
(node:27610) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at convertError (/home/joe/bin/snapmaker-luban-4.4.0-linux-x64/resources/app/node_modules/workerpool/src/worker.js:72:17)
    at /home/joe/bin/snapmaker-luban-4.4.0-linux-x64/resources/app/node_modules/workerpool/src/worker.js:142:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:27610) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27610) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2022-10-13T23:12:19.366Z - error service:TaskManager {}
`
It also leaves 5 snapmaker-luban processes and 1 chrome-sandbox, even on a clean exit.

This is on a Dell desktop with Debian 10.13 64 bit, 16 G mem, Intel® Core™ i7-4770 CPU @ 3.40GHz × 8, Intel Haswell Desktop graphics, Gnome 3.30.2 
I went through many of the issues described by ThumbOne at https://forum.snapmaker.com/t/luban-is-now-a-web-service/27087 , eventually downloading the tar file and installing into ~/bin, as the deb package would only core dump with no diagnostics

This is probably not a great format to report what I perceive as an issue, but it's the best I can do right now.  
Joe Wronski

**Comment by sumibin** [comment]
The new version should solve this problem.
