### ISSUE TITLE
Bug: can't import any files

### ISSUE THREAD

**Issue by variada** [Snapmaker/Luban#1769]
# 🐞 bug report

### Affected Version(s)
Tried (and failed) with 4.4.0 and 4.3.2

### To Reproduce
1. Go to 'Import Object'
2. Click on any .stl, .obj or .3mf file
3. Error: Failed to import this object. Please select a supported format.

We are new owners of a brand-new A350T model. Never had a 3D printer of any kind before. So not much experience with the matter.

The printer is not yet assembled, but I wanted to try out the software beforehand. 

Whenever I try to import any object file at all, I get the error above. Happens with downloads from thingiverse (tried several ones), with exports from blender (.stl) and Cura (.stl/.3mf/.obj). 

I can open the case library files. but if I export the vase example and then try to re-import it, it also fails. Therefore, I don't think it's a problem in the files themselves.

I also tried uninstalling and re-installing. Downgrading. Installing to another disk. Moving the object files to another disk. 

In the workspace, I can't add g-code files either. But I have no idea if that is the same error or another. (Should I open a different issue for that?)

### Error Message

For debugging, I tried to run the program from the command line and it gave the following error upon object import.

<pre><code>
 error api:file Failed to upload file: Unexpected token u in JSON at position 0 - SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at F:\Tools\Snapmaker Luban\resources\app\server\index.js:1:574015
    at tryCatch (F:\Tools\Snapmaker Luban\resources\app\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (F:\Tools\Snapmaker Luban\resources\app\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (F:\Tools\Snapmaker Luban\resources\app\node_modules\regenerator-runtime\runtime.js:119:21)
    at n (F:\Tools\Snapmaker Luban\resources\app\server\index.js:1:25508)
    at s (F:\Tools\Snapmaker Luban\resources\app\server\index.js:1:25719)
    at F:\Tools\Snapmaker Luban\resources\app\server\index.js:1:25778
    at new Promise (<anonymous>)
    at F:\Tools\Snapmaker Luban\resources\app\server\index.js:1:25659
    at F:\Tools\Snapmaker Luban\resources\app\server\index.js:1:574363
    at Layer.handle [as handle_request] (F:\Tools\Snapmaker Luban\resources\app\node_modules\express\lib\router\layer.js:95:5)
    at next (F:\Tools\Snapmaker Luban\resources\app\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (F:\Tools\Snapmaker Luban\resources\app\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (F:\Tools\Snapmaker Luban\resources\app\node_modules\express\lib\router\layer.js:95:5)
    at F:\Tools\Snapmaker Luban\resources\app\node_modules\express\lib\router\index.js:281:22
</code></pre>

Expected behavior
Objects get imported.

## 🌍  Your Environment

**Platform:**
<pre><code>
- Operating System: [Windows 11 x64]
- Printer: [Snapmaker A350T]
</code></pre>

**Comment by sumibin** [comment]
![image](https://user-images.githubusercontent.com/34013829/226622651-927fd3eb-586c-466f-b26e-97a9f17b5939.png)
Resetting the configuration should fix the problem.
