### ISSUE TITLE
Bug: arm64 build requires rosetta to be installed in 3d printing

### ISSUE THREAD

**Issue by oizone** [Snapmaker/Luban#2460]
# 🐞 bug report

### Affected Version(s)
 The issue is caused by version 4.10.2

### Is this a regression?

Not working with older versions either

### To Reproduce
1. Using macos arm64 without rosetta installed
2. Go to '3d printing'
3. Click on 'open stl'
4. UI hangs at 75%

server.log error
<pre><code>
2024-02-04T10:52:41.588Z - error uncaughtException: spawn Unknown system error -86
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at Object.spawn (node:child_process:707:9)
    at Slicer.slice (/Applications/Snapmaker Luban.app/Contents/Resources/app/src/server/index.js:2:1014398)
    at Slicer.end (/Applications/Snapmaker Luban.app/Contents/Resources/app/src/server/index.js:2:1015201)
    at /Applications/Snapmaker Luban.app/Contents/Resources/app/src/server/index.js:2:852808
    at handleCheckModel (/Applications/Snapmaker Luban.app/Contents/Resources/app/src/server/index.js:2:853114)
    at t.value [as channelMiddleware] (/Applications/Snapmaker Luban.app/Contents/Resources/app/src/server/index.js:2:194915)
    at /Applications/Snapmaker Luban.app/Contents/Resources/app/src/server/index.js:2:196160
    at Socket.<anonymous> (/Applications/Snapmaker Luban.app/Contents/Resources/app/src/server/index.js:2:194347)
    at Socket.emit (node:events:394:28)
    at Socket.emitUntyped (/Applications/Snapmaker Luban.app/Contents/Resources/app/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Applications/Snapmaker Luban.app/Contents/Resources/app/node_modules/socket.io/dist/socket.js:614:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
2024-02-04T10:52:41.588Z - error app uncaught exception Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at Object.spawn (node:child_process:707:9)
    at Slicer.slice (/Applications/Snapmaker Luban.app/Contents/Resources/app/src/server/index.js:2:1014398)
    at Slicer.end (/Applications/Snapmaker Luban.app/Contents/Resources/app/src/server/index.js:2:1015201)
    at /Applications/Snapmaker Luban.app/Contents/Resources/app/src/server/index.js:2:852808
    at handleCheckModel (/Applications/Snapmaker Luban.app/Contents/Resources/app/src/server/index.js:2:853114)
    at t.value [as channelMiddleware] (/Applications/Snapmaker Luban.app/Contents/Resources/app/src/server/index.js:2:194915)
    at /Applications/Snapmaker Luban.app/Contents/Resources/app/src/server/index.js:2:196160
    at Socket.<anonymous> (/Applications/Snapmaker Luban.app/Contents/Resources/app/src/server/index.js:2:194347)
    at Socket.emit (node:events:394:28)
    at Socket.emitUntyped (/Applications/Snapmaker Luban.app/Contents/Resources/app/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Applications/Snapmaker Luban.app/Contents/Resources/app/node_modules/socket.io/dist/socket.js:614:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
</code></pre>

Expected behavior
Was expecting the stl to be opened in the preview.

The doesn't happen if rosetta is installed, but the build should be arm64 right?

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: macOS Sonoma 14.2.1
- Printer: Snapmaker A350

</code></pre>

**Comment by neerdoc** [comment]
I have the exact same issue. I have an M2 mac and just tried building the binary locally, and the same error occurs, so I don't think the problem is that the build is not ARM64 as I do not have Rosetta installed.

There seems to be problems with Ubuntu ARM64 builds as well: #2101 

So I'm wondering if the issue is ARM64 support across the board?

I will try to dig a bit in this issue.

**Comment by neerdoc** [comment]
@oizone Maybe you should change the title? The arm64 image is in fact not arm64 as it contains x86_64 binaries that are required for the software to function. "ARM64 build is broken" would perhaps be a more correct title?

**Comment by neerdoc** [comment]
@parachvte @zjiefee 
I would love to help out with compiling this for arm64 on MacOS. 

The actual binary that throws the error first is the `cmd: ../../node_modules/@snapmaker/snapmaker-lunar/engine/MacOS/LunarMP modelrepair -v -p -j ` since it has the wrong CPU architecture.

I can only assume that all three files needs to be compiled for arm64 as they are currently x86_64:
- LunarMP
- LunarSlicer
- LunarTPP

**Comment by oizone** [comment]
> @oizone Maybe you should change the title? The arm64 image is in fact not arm64 as it contains x86_64 binaries that are required for the software to function. "ARM64 build is broken" would perhaps be a more correct title?

Well, yeah, it's not a arm64 since it has x86_64 code in it, no. But I think the topic already says this, even though a bit indirect. But anyway, I don't think changing the title will fix this :)

**Comment by neerdoc** [comment]
Is the npm package from here?
[Snapmaker/LunarSlicer](https://github.com/Snapmaker/LunarSlicer/tree/main
)? I don't find it very clear if this is the case.

**Comment by neerdoc** [comment]
This is still an issue in 4.13.0

I also tried reaching out to Snapmaker support to no avail. They simply answered: "Regarding this issue, there are no plans yet as this would require the R&D department to conduct further evaluation." and closed the ticket.

I would love to help out recompiling the missing parts.

**Comment by trevseb** [comment]
Still having this issue too. I will try to reach out to Snapmaker too. It's frustrating that my expensive Artisan printer is hobbled by their software.

**Comment by ITmaze** [comment]
This issue continues with 4.15.0 - I've been dealing with Snapmaker support since October 2024. They keep telling me that they cannot reproduce this. Yesterday I discovered what you already have, that there are x64 executables inside the application.

It appears that the source code for that is here: https://github.com/Snapmaker/LunarSlicer

I searched through that source tree for 'arm' and 'arm64' and it appears that this code has never been built on arm64 - unless the compiler doesn't need specific instructions to compile under arm64.

I strongly suspect that the actual root cause however is that the electron builder being used to package Luban hasn't been configured properly to output arm code, unless they're just dropping the binaries from LunaSlicer straight into the application.

**Comment by ITmaze** [comment]
It appears that there are two recent updates that add/fix arm64:

- https://github.com/Snapmaker/LunarSlicer/commit/5c40f1bab8a36768b836035547879bd4036576a1
- https://github.com/Snapmaker/LunarMP/commit/97025938b61112357fbf1e8af155c831854de255

**Comment by ITmaze** [comment]
From Snapmaker support, I have just received updated `Mach-O 64-bit executable arm64` binaries for the following four files which appears to resolve the issue and I can finally use Luban without Rosetta.

- LubanEngine
- LunarSlicer
- LunarTPP
- LunarMP

**Comment by gergomez** [comment]
> From Snapmaker support, I have just received updated `Mach-O 64-bit executable arm64` binaries for the following four files which appears to resolve the issue and I can finally use Luban without Rosetta.
> 
>     * LubanEngine
> 
>     * LunarSlicer
> 
>     * LunarTPP
> 
>     * LunarMP

Could you please share them? Thanks!

**Comment by ITmaze** [comment]
I'd love to, except I've not been given permission to do so. Supposedly this was going to be released with version v4.15.1, which does not appear to have been released.

I will note that there are two pre-releases of Luban, including [v4.15.1](https://github.com/Snapmaker/Luban/releases/tag/v4.15.1) and [v4.15.2](https://github.com/Snapmaker/Luban/releases/tag/4.15.2). I cannot tell you if they contain this fix or not.

I also note that it appears that Snapmaker have stopped developing Luban some time ago.

**Comment by gergomez** [comment]
> I'd love to, except I've not been given permission to do so. Supposedly this was going to be released with version v4.15.1, which does not appear to have been released.
> 
> I will note that there are two pre-releases of Luban, including [v4.15.1](https://github.com/Snapmaker/Luban/releases/tag/v4.15.1) and [v4.15.2](https://github.com/Snapmaker/Luban/releases/tag/4.15.2). I cannot tell you if they contain this fix or not.
> 
> I also note that it appears that Snapmaker have stopped developing Luban some time ago.

Yes, I've checked both v4.15.1 and v4.15.2 and only include the x86_64 builds. I'll contact tech support and try to get them to send me the files. Thank you!

**Comment by gergomez** [comment]
The tech support has provided me the files, but although Laser and CNC work without problems, 3D printing still fails when slicing. I've been able to run the command that fails from the command line with the same set of parameters and I'm getting:

[ERROR] Trying to retrieve setting with no value given: 'fill_perimeter_gaps'

Did you have to do anything else to make it work?

**Comment by gergomez** [comment]
I've been able to add the missing parameters to the `snapmaker_modify_0.def.json` under `print-settings/printing` but although with that the LunarSlicer command works, the app crashes, I suppose that when trying to parse the output for the preview.

```
--- /tmp/snapmaker_modify_0.def.json	2026-07-08 15:18:26.402267661 +0200
+++ snapmaker_modify_0.def.json	2026-07-08 15:40:45.932406803 +0200
@@ -3422,6 +3422,121 @@
                                 "efficiency"
                             ]
                         },
+                        "travel_compensate_overlapping_walls_enabled":
+                        {
+                            "label": "Compensate Wall Overlaps",
+                            "description": "Compensate the flow for parts of a wall being printed where there is already a wall in place.",
+                            "type": "bool",
+                            "default_value": true,
+                            "limit_to_extruder": "wall_x_extruder_nr",
+                            "settable_per_mesh": true,
+                            "children":
+                            {
+                                "travel_compensate_overlapping_walls_0_enabled":
+                                {
+                                    "label": "Compensate Outer Wall Overlaps",
+                                    "description": "Compensate the flow for parts of an outer wall being printed where there is already a wall in place.",
+                                    "type": "bool",
+                                    "default_value": true,
+                                    "value": "travel_compensate_overlapping_walls_enabled",
+                                    "limit_to_extruder": "wall_0_extruder_nr",
+                                    "settable_per_mesh": true,
+                                    "filter": [
+                                        "basic",
+                                        "advanced",
+                                        "accuracy"
+                                    ]
+
+                                },
+                                "travel_compensate_overlapping_walls_x_enabled":
+                                {
+                                    "label": "Compensate Inner Wall Overlaps",
+                                    "description": "Compensate the flow for parts of an inner wall being printed where there is already a wall in place.",
+                                    "type": "bool",
+                                    "default_value": true,
+                                    "value": "travel_compensate_overlapping_walls_enabled",
+                                    "limit_to_extruder": "wall_x_extruder_nr",
+                                    "settable_per_mesh": true,
+                                    "filter": [
+                                        "basic",
+                                        "advanced",
+                                        "accuracy"
+                                    ]
+
+                                },
+                                "wall_min_flow":
+                                {
+                                    "label": "Minimum Wall Flow",
+                                    "description": "Minimum allowed percentage flow for a wall line. The wall overlap compensation reduces a wall's flow when it lies close to an existing wall. Walls whose flow is less than this value will be replaced with a travel move. When using this setting you must have the wall overlap compensation enabled and also print the outer before inner walls.",
+                                    "unit": "%",
+                                    "minimum_value": "0",
+                                    "maximum_value": "100",
+                                    "default_value": 0,
+                                    "type": "float",
+                                    "settable_per_mesh": false,
+                                    "settable_per_extruder": true,
+                                    "filter": [
+                                        "basic",
+                                        "advanced",
+                                        "accuracy"
+                                    ]
+
+                                },
+                                "wall_min_flow_retract":
+                                {
+                                    "label": "Prefer Retract",
+                                    "description": "If enabled, retraction is used rather than combing for travel moves that replace walls whose flow is below the minimum flow threshold.",
+                                    "type": "bool",
+                                    "default_value": false,
+                                    "enabled": "wall_min_flow > 0",
+                                    "settable_per_mesh": false,
+                                    "settable_per_extruder": true,
+                                    "filter": [
+                                        "basic",
+                                        "advanced",
+                                        "accuracy"
+                                    ]
+                                }
+                            },
+                            "filter": [
+                                "basic",
+                                "advanced",
+                                "accuracy"
+                            ]
+
+                        },
+                        "fill_perimeter_gaps":
+                        {
+                            "label": "Fill Gaps Between Walls",
+                            "description": "Fills the gaps between walls where no walls fit.",
+                            "type": "enum",
+                            "options": {
+                                "nowhere": "Nowhere",
+                                "everywhere": "Everywhere"
+                            },
+                            "default_value": "everywhere",
+                            "limit_to_extruder": "wall_0_extruder_nr",
+                            "settable_per_mesh": true,
+                            "filter": [
+                                "basic",
+                                "advanced",
+                                "accuracy"
+                            ]
+                        },
+                        "filter_out_tiny_gaps":
+                        {
+                            "label": "Filter Out Tiny Gaps",
+                            "description": "Filter out tiny gaps to reduce blobs on outside of model.",
+                            "type": "bool",
+                            "default_value": true,
+                            "limit_to_extruder": "wall_0_extruder_nr",
+                            "settable_per_mesh": true,
+                            "filter": [
+                                "basic",
+                                "advanced",
+                                "accuracy"
+                            ]
+                        },
                         "fill_outline_gaps": {
                             "label": "Print Thin Walls",
                             "description": "Print pieces of the model which are horizontally thinner than the nozzle size.",
@@ -6376,6 +6491,19 @@
                                 "surface_quality"
                             ]
                         },
+                        "outer_inset_first":
+                        {
+                            "label": "Outer Before Inner Walls",
+                            "description": "Prints walls in order of outside to inside when enabled. This can help improve dimensional accuracy in X and Y when using a high viscosity plastic like ABS; however it can decrease outer surface print quality, especially on overhangs.",
+                            "type": "bool",
+                            "default_value": false,
+                            "enabled": "wall_0_extruder_nr == wall_x_extruder_nr",
+                            "settable_per_mesh": true,
+                            "filter": [
+                                "advanced",
+                                "accuracy"
+                            ]
+                        },
                         "alternate_extra_perimeter": {
                             "label": "Alternate Extra Wall",
                             "description": "Prints an extra wall at every other layer. This way infill gets caught between these extra walls, resulting in stronger prints.",

```

**Comment by ITmaze** [comment]
When I finally got the fixed binaries and discovered the same error as you describe, I'd invested eight months and exchanged 67 emails on the topic with Snapmaker support. When I discovered that the included examples didn't work and only extremely trivial STLs would slice, and Snapmaker support advised me that the developers were not interested in solving this issue, apparently leadership got involved, I stopped caring.

As an interim measure, I intend to use Luban as a "console" and do my slicing and g-code generation elsewhere. I'm attempting to determine if there is an existing console/controller I can use instead of Luban, and if I find it, or write it, I'll be done with Luban. It's a shame, since it's the only tool I'm aware of that handles all three modes out of the box (Laser, CNC and 3D printing).

I note that the attached controller resets the job zero on laser jobs, so if you've carefully configured your work, the controller happily resets it and crashes into your work, ultimately the reason I'm moving away from using it as an actual controller.

**Comment by gergomez** [comment]
Have you find any alternative that would let you use the 4th axis for Laser and CNC engraving? That's the main reason I use Luban. Also having the 3dprinting module in the same software was pretty convenient.
