### ISSUE TITLE
Luban will not start correctly in verbose mode

### ISSUE THREAD

**Issue by spontaniel** [Snapmaker/Luban#929]
# 🐞 bug report
Luban will not start correctly in verbose mode

# Affected Version(s)
Luban 3.14.0-1789

# To Reproduce
## Steps to reproduce the behavior:
1. open a terminal window
2. start luban via _**snapmaker-luban -v**_
3. the terminal window shows this output and no application window opens:
<pre>
user@host:~$ snapmaker-luban -v
Clearing folder /home/user/.config/snapmaker-luban/Tmp
Removing files: 
Clearing folder /home/user/.config/snapmaker-luban/Sessions
Removing files: 
(node:355946) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'level' of undefined
    at Module.D (/opt/Snapmaker Luban/resources/app/server/index.js:1:523940)
    at /opt/Snapmaker Luban/resources/app/server-cli.js:48:25
    at new Promise (<anonymous>)
    at launchServer (/opt/Snapmaker Luban/resources/app/server-cli.js:44:10)
    at _callee$ (/opt/Snapmaker Luban/resources/app/main.js:631:46)
    at tryCatch (/opt/Snapmaker Luban/resources/app/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/opt/Snapmaker Luban/resources/app/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/opt/Snapmaker Luban/resources/app/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/opt/Snapmaker Luban/resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/opt/Snapmaker Luban/resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /opt/Snapmaker Luban/resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /opt/Snapmaker Luban/resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at createWindow (/opt/Snapmaker Luban/resources/app/main.js:702:17)
(node:355946) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:355946) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
</pre>

## Expected behavior
luban starts in verbose mode

## 🌍  Environment

**Platform:**
<pre>
Ubuntu 20.04
luban deb package
||/ Name            Version      Architecture Description
+++-===============-============-============-=================================
ii  snapmaker-luban 3.14.0-1789  amd64
</pre>

**Comment by jane-rose** [comment]
@parachvte
